### ISSUE TITLE
exec user process caused "exec format error"

### ISSUE THREAD

**Issue by DanielRamosAcosta** [rvben/rpi-abstruse#1]
When I start the container in my Raspberry, it gives me the following error:

```
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
standard_init_linux.go:190: exec user process caused "exec format error"
```

Here is the `docker-compose.yml` that I'm using:

```yml
version: '2.1'
services:
  abstruse:
    image: rvben/rpi-abstruse
    container_name: abstruse
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - $HOME/data/abstruse/config:/root/.abstruse
    network_mode: host
    restart: always
    ports:
     - 6500:6500
```
